[2025-09-24T00:47:25.862+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-24T00:47:25.874+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task manual__2025-09-24T00:47:09.965563+00:00 [queued]>
[2025-09-24T00:47:25.877+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task manual__2025-09-24T00:47:09.965563+00:00 [queued]>
[2025-09-24T00:47:25.877+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-24T00:47:25.882+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_model_task> on 2025-09-24 00:47:09.965563+00:00
[2025-09-24T00:47:25.893+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-24T00:47:25.895+0000] {standard_task_runner.py:63} INFO - Started process 270 to run task
[2025-09-24T00:47:25.895+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1', 'load_model_task', 'manual__2025-09-24T00:47:09.965563+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp0p4zcszz']
[2025-09-24T00:47:25.897+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask load_model_task
[2025-09-24T00:47:25.925+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab1.load_model_task manual__2025-09-24T00:47:09.965563+00:00 [running]> on host 01ca18496a79
[2025-09-24T00:47:25.981+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Airflow_Lab1' AIRFLOW_CTX_TASK_ID='load_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T00:47:09.965563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-24T00:47:09.965563+00:00'
[2025-09-24T00:47:25.982+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-24T00:47:26.014+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-24T00:47:26.015+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/lab.py", line 102, in load_hierarchical_model
    predictions = loaded_model.fit_predict(df)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/cluster/_agglomerative.py", line 1116, in fit_predict
    return super().fit_predict(X, y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 695, in fit_predict
    self.fit(X, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/cluster/_agglomerative.py", line 990, in fit
    X = validate_data(self, X, ensure_min_samples=2)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2954, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1128, in check_array
    raise ValueError(
ValueError: Found array with 1 sample(s) (shape=(1, 3)) while a minimum of 2 is required by AgglomerativeClustering.
[2025-09-24T00:47:26.026+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Lab1, task_id=load_model_task, run_id=manual__2025-09-24T00:47:09.965563+00:00, execution_date=20250924T004709, start_date=20250924T004725, end_date=20250924T004726
[2025-09-24T00:47:26.034+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task load_model_task (Found array with 1 sample(s) (shape=(1, 3)) while a minimum of 2 is required by AgglomerativeClustering.; 270)
[2025-09-24T00:47:26.076+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-24T00:47:26.086+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T00:47:26.086+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
